const ShortsData = [
  {
    id: 1,
    video_src: "./shorts/boat.mp4",
    thumbnail_src: "<fixed_photo>",
    thumbnail_gif_src: "<gif_photo>",
    title: "Did Iran conduct underground nuclear test on Saturday night?.....",
  },
  {
    id: 2,
    video_src: "./shorts/cars.mp4",
    thumbnail_src: "<fixed_photo>",
    thumbnail_gif_src: "<gif_photo>",
    title: "Did Iran conduct underground nuclear test on Saturday night?.....",
  },
  {
    id: 3,
    video_src: "./shorts/firework.mp4",
    thumbnail_src: "<fixed_photo>",
    thumbnail_gif_src: "<gif_photo>",
    title: "Did Iran conduct underground nuclear test on Saturday night?.....",
  },
  {
    id: 4,
    video_src: "./shorts/loard.mp4",
    thumbnail_src: "<fixed_photo>",
    thumbnail_gif_src: "<gif_photo>",
    title: "Did Iran conduct underground nuclear test on Saturday night?.....",
  },
  {
    id: 5,
    video_src: "./shorts/bluesmoke.mp4",
    thumbnail_src: "<fixed_photo>",
    thumbnail_gif_src: "<gif_photo>",
    title: "Did Iran conduct underground nuclear test on Saturday night?.....",
  },
  {
    id: 6,
    video_src: "./shorts/redsmoke.mp4",
    thumbnail_src: "<fixed_photo>",
    thumbnail_gif_src: "<gif_photo>",
    title: "Did Iran conduct underground nuclear test on Saturday night?.....",
  },
  {
    id: 7,
    video_src: "./shorts/ship.mp4",
    thumbnail_src: "<fixed_photo>",
    thumbnail_gif_src: "<gif_photo>",
    title: "Did Iran conduct underground nuclear test on Saturday night?.....",
  },
  {
    id: 8,
    video_src: "./shorts/water.mp4",
    thumbnail_src: "<fixed_photo>",
    thumbnail_gif_src: "<gif_photo>",
    title: "Did Iran conduct underground nuclear test on Saturday night?.....",
  },
  {
    id: 9,
    video_src: "./shorts/xmas.mp4",
    thumbnail_src: "<fixed_photo>",
    thumbnail_gif_src: "<gif_photo>",
    title: "Did Iran conduct underground nuclear test on Saturday night?.....",
  },
];
export default ShortsData;
